//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfRESTful.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public int Id { get; set; }
        public string SourceCurrency { get; set; }
        public string TargetCurrency { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountWithExchangeRate { get; set; }
    }
}
